# Generated by Django 4.1.6 on 2023-02-26 08:42

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=user.models.get_default_profile_image_path, max_length=255, null=True, upload_to=user.models.get_profile_image_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created date'),
        ),
    ]
