# Generated by Django 4.1.6 on 2023-03-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_chatroom_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='parent_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatroom.message'),
        ),
    ]
